from tkinter import *
from tkinter import messagebox
def inserta():
    #messagebox.showinfo("пример ввода\вывода", message.get())
    #print(message.get())
    a=messagea.get()
    print(a)    
def insertb():
    #messagebox.showinfo("пример ввода\вывода", message.get())
    #print(message.get())   
    b=messageb.get()
    print(b)    
def insertc():
    #messagebox.showinfo("пример ввода\вывода", message.get())
    #print(message.get())
    c=messagec.get()
    print(c)    
def insertd():
    #messagebox.showinfo("пример ввода\вывода", message.get())
    #print(message.get())
    d=messaged.get()
    print(d)    
root = Tk()
messagea=StringVar()
messageb=StringVar()
messagec=StringVar()
messaged=StringVar()
e1=Entry(root,width=16,textvariable=messagea)
e2=Entry(root,width=16,textvariable=messageb)
e3=Entry(root,width=16,textvariable=messagec)
e4=Entry(root,width=16,textvariable=messaged)
#a=e1.get()
#.place(x=5,y=20) 
root.geometry('220x130')
but1 = Button(bg='red',text="Дата                    ", command=inserta).place(x=120,y=20)
but2=Button(bg='pink',text="Вес                      ",command=insertb).place(x=120,y=45)
but3=Button(bg='blue',text="Уровень сахара",command=insertc).place(x=120,y=70)
but4=Button(bg='green',text="Комментарий   ",command=insertd).place(x=120,y=95)
#but2=Button(bg='blue',text="Уровень сахара",insertc).place(x=120,y=70)
#but3.place(x=120,y=95)
e1.place(x=5,y=20)
e2.place(x=5,y=45)
e3.place(x=5,y=70)
e4.place(x=5,y=95)
root.mainloop
